// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJYXWxAhNXmXnYMMaq9NMCGuwXIqaQ-f4',
    appId: '1:685597780993:web:31806261b8e35b8e61e400',
    messagingSenderId: '685597780993',
    projectId: 'aplikasihrdnsi',
    authDomain: 'aplikasihrdnsi.firebaseapp.com',
    storageBucket: 'aplikasihrdnsi.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2TNKHCRDVp-P4dOGIG8Xq6SKdgkVYJBM',
    appId: '1:685597780993:android:ba1f8136c27f750861e400',
    messagingSenderId: '685597780993',
    projectId: 'aplikasihrdnsi',
    storageBucket: 'aplikasihrdnsi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU7tSeXPGpj-xj8t3fy2ojeaNgD4b9qj0',
    appId: '1:685597780993:ios:df0f0cf63e00d29f61e400',
    messagingSenderId: '685597780993',
    projectId: 'aplikasihrdnsi',
    storageBucket: 'aplikasihrdnsi.appspot.com',
    iosClientId: '685597780993-1n9ivo7ddhhcqb1so654t4pes82u2a67.apps.googleusercontent.com',
    iosBundleId: 'com.nsi.aplikasihrd.aplikasiHrd',
  );
}
